# Generated by Django 6.0.5 on 2026-06-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('jobseeker', 'jobseeker'), ('company', 'company')], max_length=30)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('skills', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=30)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.user')),
            ],
        ),
    ]
