# Generated by Django 6.0.6 on 2026-06-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_website', models.URLField()),
                ('industry_type', models.CharField(max_length=30)),
                ('company_size', models.CharField(max_length=30)),
                ('about_company', models.TextField()),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('recruiter_name', models.CharField(max_length=30)),
                ('company_linkedin_url', models.URLField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.user')),
            ],
        ),
    ]
