"""
QUE  128: HANDLE FILE NOT FOUND EXCEPTION
WRITE A FUNCTION READ_FILE(FILENAME) THAT ATTEMPTS TO OPEN AND READ A FILE. IF THE FILE DOES NOT EXIST, IT SHOULD RAISE A FILENOTFOUNDERROR AND PRINT A FRIENDLY ERROR MESSAGE TO THE USER.

"""