"""
QUE  104: CONVERT A DICTIONARY TO A LIST OF TUPLES
WRITE A FUNCTION DICT_TO_TUPLES(D) THAT ACCEPTS A DICTIONARY AND RETURNS A LIST OF TUPLES WHERE EACH TUPLE CONTAINS A KEY-VALUE PAIR FROM THE DICTIONARY.

"""