"""
QUE   103: CHECK IF A LIST CONTAINS ONLY UNIQUE ELEMENTS
WRITE A FUNCTION IS_UNIQUE(LST) THAT ACCEPTS A LIST AND RETURNS TRUE IF ALL THE ELEMENTS ARE UNIQUE, AND FALSE IF ANY ELEMENT APPEARS MORE THAN ONCE.

"""