"""
QUE  118: READ AND PARSE CSV FILE
WRITE A FUNCTION READ_CSV_FILE(FILENAME) THAT READS A CSV FILE AND RETURNS THE DATA AS A LIST OF DICTIONARIES, WHERE THE KEYS ARE THE COLUMN NAMES AND THE VALUES ARE THE CORRESPONDING ROW VALUES.

"""