"""
QUE  119: COPY CONTENT FROM ONE FILE TO ANOTHER
WRITE A FUNCTION COPY_FILE_CONTENT(SOURCE_FILENAME, DESTINATION_FILENAME) THAT COPIES THE CONTENT OF ONE FILE TO ANOTHER. ENSURE THE DESTINATION FILE IS CREATED IF IT DOESN'T EXIST.

"""