"""
QUE  106: SPLIT A LIST INTO TWO LISTS
WRITE A FUNCTION SPLIT_LIST(LST) THAT ACCEPTS A LIST AND SPLITS IT INTO TWO LISTS. THE FIRST LIST SHOULD CONTAIN THE FIRST HALF OF THE ELEMENTS, AND THE SECOND LIST SHOULD CONTAIN THE SECOND HALF.

"""