"""
QUE  120: CREATE A DICTIONARY OF WORD FREQUENCIES FROM A FILE
WRITE A FUNCTION WORD_FREQUENCY_FROM_FILE(FILENAME) THAT ACCEPTS A FILE NAME, READS THE FILE, AND RETURNS A DICTIONARY WHERE THE KEYS ARE UNIQUE WORDS IN THE FILE, AND THE VALUES ARE THE FREQUENCY OF EACH WORD.

"""