"""
QUE  101: UPDATE DICTIONARY VALUES BASED ON ANOTHER DICTIONARY
WRITE A FUNCTION UPDATE_DICT(D1, D2) THAT ACCEPTS TWO DICTIONARIES. IT SHOULD UPDATE THE VALUES OF D1 WITH THE VALUES FROM D2 WHERE THE KEYS MATCH. IF A KEY FROM D2 DOES NOT EXIST IN D1, IT SHOULD BE ADDED.

"""