"""
QUE  105: FIND MISSING NUMBERS IN A LIST
WRITE A FUNCTION FIND_MISSING_NUMBERS(LST, N) THAT ACCEPTS A LIST OF INTEGERS AND A NUMBER N. THE LIST CONTAINS INTEGERS FROM 1 TO N WITH SOME NUMBERS MISSING. THE FUNCTION SHOULD RETURN A LIST OF THE MISSING NUMBERS.

"""