"""
QUE  112: REMOVE KEYS FROM DICTIONARY BASED ON A CONDITION
WRITE A FUNCTION REMOVE_KEYS_BY_CONDITION(D, CONDITION) THAT ACCEPTS A DICTIONARY AND REMOVES THE KEYS WHERE THE CORRESPONDING VALUES SATISFY A CONDITION. FOR EXAMPLE, REMOVING ALL KEYS WITH VALUES GREATER THAN A SPECIFIC THRESHOLD.

"""