"""
QUE  113: FIND THE UNION OF TWO LISTS
WRITE A FUNCTION FIND_UNION(LST1, LST2) THAT ACCEPTS TWO LISTS AND RETURNS A NEW LIST THAT CONTAINS THE UNION OF BOTH LISTS (ALL ELEMENTS FROM BOTH LISTS WITHOUT DUPLICATES).

"""