"""
QUE  134: HANDLE INVALID USER INPUT WITH CUSTOM EXCEPTION
WRITE A FUNCTION GET_INTEGER_INPUT() THAT PROMPTS THE USER TO INPUT AN INTEGER. IF THE USER ENTERS SOMETHING OTHER THAN AN INTEGER, RAISE A VALUEERROR AND PRINT A MESSAGE ASKING THE USER TO ENTER A VALID INTEGER

"""