"""
QUE  129: USE A TRY-EXCEPT BLOCK FOR HANDLING MULTIPLE EXCEPTIONS
WRITE A FUNCTION DIVIDE_NUMBERS(A, B) THAT TAKES TWO NUMBERS AS INPUT AND DIVIDES THEM. USE A TRY-EXCEPT BLOCK TO HANDLE BOTH DIVISION BY ZERO AND INVALID INPUT TYPES (E.G., STRING INPUTS) BY RAISING APPROPRIATE EXCEPTIONS.

"""