"""
QUE  132: USE FINALLY BLOCK FOR RESOURCE CLEANUP
WRITE A FUNCTION OPEN_AND_CLOSE_FILE(FILENAME) THAT OPENS A FILE, PERFORMS SOME READ/WRITE OPERATIONS, AND ENSURES THAT THE FILE IS CLOSED PROPERLY IN THE FINALLY BLOCK, EVEN IF AN EXCEPTION OCCURS DURING THE OPERATIONS.

"""