"""
QUE  130: CREATE A MODULE FOR TEMPERATURE CONVERSION
CREATE A MODULE CALLED TEMPERATURE.PY THAT CONTAINS FUNCTIONS TO CONVERT TEMPERATURES BETWEEN CELSIUS, FAHRENHEIT, AND KELVIN. THEN, WRITE A SCRIPT THAT IMPORTS THIS MODULE AND PERFORMS THE CONVERSION, HANDLING INVALID TEMPERATURE VALUES WITH EXCEPTION HANDLING.

"""