"""
QUE  131: RAISE A CUSTOM EXCEPTION
WRITE A FUNCTION VALIDATE_AGE(AGE) THAT RAISES A CUSTOM EXCEPTION AGEERROR IF THE AGE IS LESS THAN 0 OR GREATER THAN 150. DEFINE THE AGEERROR CLASS AND HANDLE IT IN THE MAIN FUNCTION WHEN CALLING VALIDATE_AGE().

"""