"""
QUE  135: CATCHING MULTIPLE EXCEPTIONS WITH SPECIFIC MESSAGES
WRITE A FUNCTION PERFORM_OPERATION(A, B, OPERATION) THAT PERFORMS A MATHEMATICAL OPERATION (ADDITION, SUBTRACTION, ETC.) BASED ON THE INPUT. USE EXCEPTION HANDLING TO CATCH AND PRINT SPECIFIC MESSAGES FOR ZERODIVISIONERROR, VALUEERROR, AND TYPEERROR."""