"""
QUE  133: CREATE A MODULE FOR BASIC BANKING OPERATIONS
CREATE A MODULE BANKING.PY THAT HAS FUNCTIONS FOR CHECKING ACCOUNT BALANCE, WITHDRAWING MONEY, AND DEPOSITING MONEY. IN THE WITHDRAWAL FUNCTION, RAISE AN EXCEPTION IF THE USER TRIES TO WITHDRAW MORE THAN THE AVAILABLE BALANCE. USE THIS MODULE IN ANOTHER SCRIPT AND HANDLE ANY EXCEPTIONS RELATED TO INSUFFICIENT FUNDS.

"""