"""
QUE  121: APPEND TO AN EXISTING FILE
WRITE A FUNCTION APPEND_TO_FILE(FILENAME, CONTENT) THAT APPENDS THE PROVIDED CONTENT TO AN EXISTING FILE. IF THE FILE DOESN'T EXIST, IT SHOULD BE CREATED.

"""