"""
QUE  127: CREATE A CUSTOM MODULE FOR ARITHMETIC OPERATIONS
WRITE A PYTHON MODULE CALLED ARITHMETIC.PY THAT CONTAINS FUNCTIONS FOR ADDITION, SUBTRACTION, MULTIPLICATION, AND DIVISION. THEN, IMPORT THIS MODULE IN A SEPARATE SCRIPT AND USE IT TO PERFORM BASIC ARITHMETIC OPERATIONS. HANDLE DIVISION BY ZERO USING EXCEPTION HANDLING.

"""