"""
QUE  109: MERGE TWO LISTS INTO A DICTIONARY WITH LIST INDICES AS KEYS
WRITE A FUNCTION MERGE_LISTS_INTO_DICT(LIST1, LIST2) THAT ACCEPTS TWO LISTS OF EQUAL LENGTH AND MERGES THEM INTO A DICTIONARY WHERE THE KEYS ARE THE INDICES (0 TO N-1) AND THE VALUES ARE THE ELEMENTS FROM BOTH LISTS.

"""