"""
QUE  126: IMPORT SPECIFIC FUNCTIONS FROM A MODULE
WRITE A FUNCTION USE_SPECIFIC_FUNCTION() THAT IMPORTS ONLY THE SQRT FUNCTION FROM THE MATH MODULE AND CALCULATES THE SQUARE ROOT OF A GIVEN NUMBER. HANDLE ANY EXCEPTIONS IF THE INPUT IS INVALID.

"""