"""
QUE  114: CREATE A DICTIONARY OF SQUARES FROM A LIST
WRITE A FUNCTION CREATE_SQUARE_DICT(LST) THAT ACCEPTS A LIST OF NUMBERS AND RETURNS A DICTIONARY WHERE THE KEYS ARE THE NUMBERS AND THE VALUES ARE THEIR SQUARES.

"""