"""
QUE  108: CREATE A FREQUENCY DICTIONARY FROM A LIST
WRITE A FUNCTION CREATE_FREQUENCY_DICT(LST) THAT ACCEPTS A LIST AND RETURNS A DICTIONARY WHERE THE KEYS ARE THE ELEMENTS OF THE LIST, AND THE VALUES ARE THE COUNT OF HOW OFTEN EACH ELEMENT APPEARS.

"""