"""
QUE  115: CONVERT A LIST TO A DICTIONARY WITH INDEXES AS KEYS
WRITE A FUNCTION LIST_TO_DICT(LST) THAT ACCEPTS A LIST AND RETURNS A DICTIONARY WHERE THE KEYS ARE THE INDICES OF THE LIST, AND THE VALUES ARE THE ELEMENTS AT THOSE INDICES.

"""