"""
QUE  110: COUNT THE NUMBER OF EVEN AND ODD NUMBERS IN A LIST
WRITE A FUNCTION COUNT_EVEN_ODD(LST) THAT ACCEPTS A LIST OF INTEGERS AND RETURNS A DICTIONARY WITH THE COUNT OF EVEN NUMBERS AND ODD NUMBERS.

"""