"""
QUE  59: SUM OF POSITIVE AND NEGATIVE NUMBERS
WRITE A FUNCTION SUM_POSITIVE_AND_NEGATIVE(LST) THAT ACCEPTS A LIST OF INTEGERS AND RETURNS A TUPLE WITH THE SUM OF ALL POSITIVE NUMBERS AND THE SUM OF ALL NEGATIVE NUMBERS.

"""