"""
QUE  57: FIND MISSING NUMBER IN SEQUENCE
WRITE A FUNCTION FIND_MISSING_NUMBER(NUMBERS) THAT ACCEPTS A LIST OF NUMBERS FROM 1 TO N, WITH ONE NUMBER MISSING. THE FUNCTION SHOULD RETURN THE MISSING NUMBER.

"""