"""
QUE  51: EMAIL ADDRESS VALIDATOR
WRITE A FUNCTION IS_VALID_EMAIL(EMAIL) THAT ACCEPTS AN EMAIL ADDRESS AS A STRING AND CHECKS IF IT FOLLOWS A VALID FORMAT (CONTAINS "@" AND "."). RETURN TRUE IF VALID, OTHERWISE FALSE.

"""