"""
QUE  55: REMOVE WHITESPACE FROM A STRING :WRITE A FUNCTION REMOVE_WHITESPACE(S) THAT ACCEPTS A STRING AND RETURNS THE STRING WITH ALL LEADING, TRAILING, AND EXTRA SPACES BETWEEN WORDS REMOVED.

"""