"""
QUE  54: STUDENT GRADING SYSTEM
WRITE A FUNCTION CALCULATE_GRADE(MARKS) THAT ACCEPTS THE MARKS OF A STUDENT (OUT OF 100) AND RETURNS THE GRADE AS PER THE FOLLOWING SCALE:

90 AND ABOVE: "A"
80 TO 89: "B"
70 TO 79: "C"
60 TO 69: "D"
BELOW 60: "F"

"""