"""
QUE  53: REMOVE DUPLICATE WORDS
WRITE A FUNCTION REMOVE_DUPLICATE_WORDS(SENTENCE) THAT ACCEPTS A STRING WITH MULTIPLE WORDS AND RETURNS A NEW STRING WHERE ALL DUPLICATE WORDS ARE REMOVED WHILE MAINTAINING THE ORIGINAL ORDER OF WORDS.

"""