"""
QUE  66: CONCATENATE STRINGS WITH A SEPARATOR
WRITE A FUNCTION CONCATENATE_WITH_SEPARATOR(LST, SEPARATOR) THAT ACCEPTS A LIST OF STRINGS AND A SEPARATOR STRING, THEN RETURNS A NEW STRING WHERE ALL ELEMENTS OF THE LIST ARE JOINED USING THE SEPARATOR.

"""
l1=["Hiren","Gondaliya"]

f_name = "_".join(l1)
print(f_name)