"""
QUE  69: FIND THE FIRST REPEATING ELEMENT
WRITE A FUNCTION FIND_FIRST_REPEATING_ELEMENT(LST) THAT ACCEPTS A LIST OF INTEGERS AND RETURNS THE FIRST ELEMENT THAT REPEATS. IF NO ELEMENT REPEATS, RETURN NONE.

"""