"""
QUE  65: COUNT SPECIFIC CHARACTER OCCURRENCES
WRITE A FUNCTION COUNT_CHARACTER(STRING, CHAR) THAT ACCEPTS A STRING AND A CHARACTER, AND RETURNS THE NUMBER OF TIMES THE CHARACTER APPEARS IN THE STRING.

"""