"""
QUE  60: CHECK IF A STRING IS A SUBSTRING
WRITE A FUNCTION IS_SUBSTRING(STR1, STR2) THAT ACCEPTS TWO STRINGS AND CHECKS IF THE FIRST STRING IS A SUBSTRING OF THE SECOND STRING. RETURN TRUE OR FALSE.

"""