"""
QUE  68: GENERATE RANDOM PASSWORD
WRITE A FUNCTION GENERATE_PASSWORD(LENGTH) THAT ACCEPTS A LENGTH AS AN ARGUMENT AND RETURNS A RANDOMLY GENERATED PASSWORD OF THAT LENGTH CONSISTING OF UPPERCASE LETTERS, LOWERCASE LETTERS, AND DIGITS.

"""