"""
QUE  61: SORT LIST OF TUPLES BY SECOND ELEMENT
WRITE A FUNCTION SORT_TUPLES(LST) THAT ACCEPTS A LIST OF TUPLES, AND SORTS THE LIST BASED ON THE SECOND ELEMENT OF EACH TUPLE IN ASCENDING ORDER.

"""