"""
QUE  78: CALCULATE SIMPLE INTEREST
WRITE A FUNCTION CALCULATE_SIMPLE_INTEREST(PRINCIPAL, RATE, TIME) THAT ACCEPTS THE PRINCIPAL, RATE OF INTEREST, AND TIME, AND RETURNS THE CALCULATED SIMPLE INTEREST.

"""