"""
QUE  77: COUNT THE OCCURRENCE OF EACH CHARACTER
WRITE A FUNCTION COUNT_CHARACTER_OCCURRENCES(STRING) THAT ACCEPTS A STRING AND RETURNS A DICTIONARY WITH THE COUNT OF EACH CHARACTER IN THE STRING.

"""