"""
QUE  72: CHECK IF TWO LISTS ARE ANAGRAMS
WRITE A FUNCTION ARE_ANAGRAMS(LIST1, LIST2) THAT ACCEPTS TWO LISTS OF STRINGS AND CHECKS IF ONE LIST IS AN ANAGRAM OF THE OTHER (I.E., THE LISTS CONTAIN THE SAME ELEMENTS, BUT POSSIBLY IN DIFFERENT ORDERS).

"""