"""
QUE  71: MERGE TWO DICTIONARIES
WRITE A FUNCTION MERGE_DICTS(DICT1, DICT2) THAT ACCEPTS TWO DICTIONARIES AND RETURNS A SINGLE DICTIONARY THAT CONTAINS THE MERGED KEY-VALUE PAIRS FROM BOTH DICTIONARIES.

"""