"""
QUE  87: MERGE TWO DICTIONARIES
WRITE A FUNCTION MERGE_DICTS(DICT1, DICT2) THAT ACCEPTS TWO DICTIONARIES AND MERGES THEM INTO ONE. IF THERE ARE OVERLAPPING KEYS, THE VALUES FROM THE SECOND DICTIONARY SHOULD OVERWRITE THE VALUES FROM THE FIRST.

"""