"""
QUE  89: CREATE A DICTIONARY FROM TWO LISTS
WRITE A FUNCTION CREATE_DICT(KEYS, VALUES) THAT ACCEPTS TWO LISTS: ONE CONTAINING KEYS AND THE OTHER CONTAINING VALUES. THE FUNCTION SHOULD RETURN A DICTIONARY WITH THE KEYS FROM THE FIRST LIST AND THE CORRESPONDING VALUES FROM THE SECOND LIST.

"""