"""
QUE  83: COUNT OCCURRENCES OF WORDS IN A SENTENCE
WRITE A FUNCTION COUNT_WORD_OCCURRENCES(SENTENCE) THAT ACCEPTS A SENTENCE AND RETURNS A DICTIONARY WITH THE COUNT OF EACH WORD IN THE SENTENCE.

"""