"""
QUE  88: COUNT THE OCCURRENCE OF EACH ITEM IN A LIST
WRITE A FUNCTION COUNT_ITEMS(LST) THAT ACCEPTS A LIST OF ITEMS AND RETURNS A DICTIONARY WHERE THE KEYS ARE THE ITEMS FROM THE LIST, AND THE VALUES ARE THE NUMBER OF TIMES EACH ITEM APPEARS.

"""