"""
QUE  82: CHECK IF TWO STRINGS ARE ANAGRAMS
WRITE A FUNCTION IS_ANAGRAM(STR1, STR2) THAT ACCEPTS TWO STRINGS AND CHECKS IF THEY ARE ANAGRAMS OF EACH OTHER (I.E., THEY CONTAIN THE SAME CHARACTERS IN DIFFERENT ORDERS).

"""