"""
QUE  81: CREATE A DICTIONARY FROM TWO LISTS
WRITE A FUNCTION CREATE_DICT(KEYS, VALUES) THAT ACCEPTS TWO LISTS, KEYS AND VALUES, AND RETURNS A DICTIONARY WHERE THE KEYS ARE FROM THE FIRST LIST AND THE VALUES ARE FROM THE SECOND LIST.

"""