"""
QUE  86: FIND THE MOST FREQUENT ELEMENT IN A LIST
WRITE A FUNCTION FIND_MOST_FREQUENT(LST) THAT ACCEPTS A LIST OF ELEMENTS AND RETURNS THE MOST FREQUENT ELEMENT IN THE LIST. IF THERE ARE MULTIPLE FREQUENT ELEMENTS, RETURN ANY ONE OF THEM.

"""