"""
QUE  93: FIND THE KEY WITH THE MAXIMUM VALUE IN A DICTIONARY
WRITE A FUNCTION FIND_MAX_KEY(D) THAT ACCEPTS A DICTIONARY AND RETURNS THE KEY THAT HAS THE HIGHEST VALUE. IF THERE ARE MULTIPLE KEYS WITH THE SAME MAXIMUM VALUE, RETURN ANY ONE OF THEM.

"""