"""
QUE  92: SUM ALL VALUES IN A DICTIONARY
WRITE A FUNCTION SUM_DICT_VALUES(D) THAT ACCEPTS A DICTIONARY WHERE THE VALUES ARE NUMBERS. THE FUNCTION SHOULD RETURN THE SUM OF ALL VALUES IN THE DICTIONARY.

"""