"""
QUE  95: COMBINE MULTIPLE LISTS INTO A DICTIONARY
WRITE A FUNCTION COMBINE_LISTS_TO_DICT(KEYS, VALUES) THAT ACCEPTS TWO LISTS, ONE CONTAINING KEYS AND THE OTHER CONTAINING VALUES. THE FUNCTION SHOULD COMBINE THEM INTO A DICTIONARY AND RETURN IT. IF THERE ARE MORE VALUES THAN KEYS, IGNORE THE EXTRA VALUES.

"""