"""
QUE  90: REMOVE DUPLICATES FROM A LIST AND KEEP ORDER
WRITE A FUNCTION REMOVE_DUPLICATES(LST) THAT ACCEPTS A LIST AND REMOVES ANY DUPLICATE ELEMENTS WHILE KEEPING THE ORIGINAL ORDER OF THE ELEMENTS.

"""