"""
QUE  96: CHECK IF A DICTIONARY CONTAINS A SPECIFIC KEY
WRITE A FUNCTION CONTAINS_KEY(D, KEY) THAT ACCEPTS A DICTIONARY AND A KEY. IT SHOULD RETURN TRUE IF THE KEY EXISTS IN THE DICTIONARY AND FALSE OTHERWISE.

"""