"""
QUE  98: FIND THE DIFFERENCE BETWEEN TWO LISTS
WRITE A FUNCTION FIND_DIFFERENCE(LST1, LST2) THAT ACCEPTS TWO LISTS AND RETURNS A NEW LIST CONTAINING ELEMENTS THAT ARE IN THE FIRST LIST BUT NOT IN THE SECOND.

"""