"""
QUE  97: FLATTEN A LIST OF LISTS
WRITE A FUNCTION FLATTEN_LIST_OF_LISTS(LST) THAT ACCEPTS A LIST OF LISTS (A NESTED LIST) AND RETURNS A FLAT LIST CONTAINING ALL THE ELEMENTS OF THE INNER LISTS.

"""