"""
QUE  99: GROUP LIST ELEMENTS BY FREQUENCY
WRITE A FUNCTION GROUP_BY_FREQUENCY(LST) THAT ACCEPTS A LIST AND GROUPS THE ELEMENTS BASED ON THEIR FREQUENCY. THE FUNCTION SHOULD RETURN A DICTIONARY WHERE THE KEYS ARE THE FREQUENCIES AND THE VALUES ARE LISTS OF ELEMENTS THAT OCCUR THAT MANY TIMES.

"""